#!/bin/bash

S3_URI=s3://yourbucket/V1__shopwise.sql
RDS_ENDPOINT=your endpoint
RDS_DB_NAME=your db name
RDS_DB_USERNAME=db username
RDS_DB_PASSWORD=db password

# Update all packages
sudo yum update -y

# Download and extract Flyway
sudo wget -qO- wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.16.0/flyway-commandline-10.16.0-linux-x64.tar.gz | tar -xvz

# Create a symbolic link to make Flyway accessible globally
sudo ln -s `pwd`/flyway-10.16.0/flyway /usr/local/bin

# Create the SQL directory for migrations
sudo mkdir sql

# Download the migration SQL script from AWS S3
sudo aws s3 cp "$S3_URI" sql/

# Run Flyway migration
flyway -url=jdbc:mysql://"$RDS_ENDPOINT":3306/"$RDS_DB_NAME" \
  -user="$RDS_DB_USERNAME" \
  -password="$RDS_DB_PASSWORD" \
  -locations=filesystem:sql \
  migrate
